Error Log Started: 2024-12-09 18:43:55.653808
==================================================

Time: 2024-12-09 18:46:52
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 02 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-02', 'year': 1997, 'timestamp': '2024-12-09 18:46:52', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611020CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 02 is invalid\n'}
==================================================

Time: 2024-12-09 18:46:54
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 06 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-06', 'year': 1997, 'timestamp': '2024-12-09 18:46:54', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611060CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 06 is invalid\n'}
==================================================

Time: 2024-12-09 18:46:57
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 09 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-09', 'year': 1997, 'timestamp': '2024-12-09 18:46:57', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611090CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 09 is invalid\n'}
==================================================

Time: 2024-12-09 18:46:59
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 15 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-15', 'year': 1997, 'timestamp': '2024-12-09 18:46:59', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611150CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 15 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:01
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 20 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-20', 'year': 1997, 'timestamp': '2024-12-09 18:47:01', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611200CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 20 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:03
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 23 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-23', 'year': 1997, 'timestamp': '2024-12-09 18:47:03', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611230CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 23 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:05
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 11, and day set to 26 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-11-26', 'year': 1997, 'timestamp': '2024-12-09 18:47:05', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199611260CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 11, and day set to 26 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:07
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 12, and day set to 11 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-12-11', 'year': 1997, 'timestamp': '2024-12-09 18:47:07', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199612110CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 12, and day set to 11 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:09
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 12, and day set to 13 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-12-13', 'year': 1997, 'timestamp': '2024-12-09 18:47:09', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199612130CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 12, and day set to 13 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:11
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 12, and day set to 19 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-12-19', 'year': 1997, 'timestamp': '2024-12-09 18:47:11', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199612190CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 12, and day set to 19 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:13
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 12, and day set to 21 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-12-21', 'year': 1997, 'timestamp': '2024-12-09 18:47:13', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199612210CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 12, and day set to 21 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:15
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1996, month set to 12, and day set to 27 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1996-12-27', 'year': 1997, 'timestamp': '2024-12-09 18:47:15', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199612270CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1996, month set to 12, and day set to 27 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:17
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 02 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-02', 'year': 1997, 'timestamp': '2024-12-09 18:47:17', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701020CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 02 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:20
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 04 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-04', 'year': 1997, 'timestamp': '2024-12-09 18:47:20', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701040CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 04 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:22
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 15 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-15', 'year': 1997, 'timestamp': '2024-12-09 18:47:22', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701150CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 15 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:24
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 21 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-21', 'year': 1997, 'timestamp': '2024-12-09 18:47:24', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701210CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 21 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:26
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 24 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-24', 'year': 1997, 'timestamp': '2024-12-09 18:47:26', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701240CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 24 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:28
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 29 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-29', 'year': 1997, 'timestamp': '2024-12-09 18:47:28', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701290CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 29 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:30
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 01, and day set to 31 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-01-31', 'year': 1997, 'timestamp': '2024-12-09 18:47:30', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199701310CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 01, and day set to 31 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:32
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 04 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-04', 'year': 1997, 'timestamp': '2024-12-09 18:47:32', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702040CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 04 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:34
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 06 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-06', 'year': 1997, 'timestamp': '2024-12-09 18:47:34', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702060CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 06 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:37
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 12 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-12', 'year': 1997, 'timestamp': '2024-12-09 18:47:37', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702120CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 12 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:39
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 14 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-14', 'year': 1997, 'timestamp': '2024-12-09 18:47:39', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702140CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 14 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:41
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 17 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-17', 'year': 1997, 'timestamp': '2024-12-09 18:47:41', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702170CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 17 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:43
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 19 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-19', 'year': 1997, 'timestamp': '2024-12-09 18:47:43', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702190CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 19 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:45
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 02, and day set to 21 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-02-21', 'year': 1997, 'timestamp': '2024-12-09 18:47:45', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199702210CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 02, and day set to 21 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:47
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 04 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-04', 'year': 1997, 'timestamp': '2024-12-09 18:47:47', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703040CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 04 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:49
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 06 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-06', 'year': 1997, 'timestamp': '2024-12-09 18:47:49', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703060CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 06 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:51
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 09 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-09', 'year': 1997, 'timestamp': '2024-12-09 18:47:51', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703090CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 09 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:53
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 11 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-11', 'year': 1997, 'timestamp': '2024-12-09 18:47:53', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703110CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 11 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:55
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 17 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-17', 'year': 1997, 'timestamp': '2024-12-09 18:47:55', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703170CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 17 is invalid\n'}
==================================================

Time: 2024-12-09 18:47:58
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 19 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-19', 'year': 1997, 'timestamp': '2024-12-09 18:47:58', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703190CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 19 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:00
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 22 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-22', 'year': 1997, 'timestamp': '2024-12-09 18:48:00', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703220CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 22 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:02
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 26 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-26', 'year': 1997, 'timestamp': '2024-12-09 18:48:02', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703260CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 26 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:04
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 03, and day set to 28 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-03-28', 'year': 1997, 'timestamp': '2024-12-09 18:48:04', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199703280CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 03, and day set to 28 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:06
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 02 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-02', 'year': 1997, 'timestamp': '2024-12-09 18:48:06', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704020CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 02 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:08
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 05 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-05', 'year': 1997, 'timestamp': '2024-12-09 18:48:08', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704050CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 05 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:10
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 09 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-09', 'year': 1997, 'timestamp': '2024-12-09 18:48:10', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704090CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 09 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:12
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 12 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-12', 'year': 1997, 'timestamp': '2024-12-09 18:48:12', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704120CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 12 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:15
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 14 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-14', 'year': 1997, 'timestamp': '2024-12-09 18:48:15', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704140CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 14 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:17
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 18 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-18', 'year': 1997, 'timestamp': '2024-12-09 18:48:17', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704180CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 18 is invalid\n'}
==================================================

Time: 2024-12-09 18:48:19
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1997, month set to 04, and day set to 28 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1997-04-28', 'year': 1997, 'timestamp': '2024-12-09 18:48:19', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199704280CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 890, in main\n    yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, attemptCounter)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/dataProcessor.py", line 127, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1997, month set to 04, and day set to 28 is invalid\n'}
==================================================

