Error Log Started: 2024-12-09 16:47:35.667575
==================================================

Time: 2024-12-09 16:49:38
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 02, and day set to 05 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-02-05', 'year': 1999, 'timestamp': '2024-12-09 16:49:38', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199902050CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 02, and day set to 05 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:40
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 02, and day set to 06 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-02-06', 'year': 1999, 'timestamp': '2024-12-09 16:49:40', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199902060CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 02, and day set to 06 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:42
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 02, and day set to 08 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-02-08', 'year': 1999, 'timestamp': '2024-12-09 16:49:42', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199902080CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 02, and day set to 08 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:45
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 02, and day set to 10 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-02-10', 'year': 1999, 'timestamp': '2024-12-09 16:49:45', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199902100CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 02, and day set to 10 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:47
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 02, and day set to 24 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-02-24', 'year': 1999, 'timestamp': '2024-12-09 16:49:47', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199902240CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 02, and day set to 24 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:49
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 02, and day set to 26 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-02-26', 'year': 1999, 'timestamp': '2024-12-09 16:49:49', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199902260CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 02, and day set to 26 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:51
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 01 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-01', 'year': 1999, 'timestamp': '2024-12-09 16:49:51', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903010CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 01 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:53
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 09 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-09', 'year': 1999, 'timestamp': '2024-12-09 16:49:53', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903090CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 09 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:55
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 17 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-17', 'year': 1999, 'timestamp': '2024-12-09 16:49:55', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903170CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 17 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:57
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 19 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-19', 'year': 1999, 'timestamp': '2024-12-09 16:49:57', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903190CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 19 is invalid\n'}
==================================================

Time: 2024-12-09 16:49:59
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 24 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-24', 'year': 1999, 'timestamp': '2024-12-09 16:49:59', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903240CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 24 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:01
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 26 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-26', 'year': 1999, 'timestamp': '2024-12-09 16:50:01', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903260CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 26 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:04
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 28 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-28', 'year': 1999, 'timestamp': '2024-12-09 16:50:04', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903280CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 28 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:06
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 30 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-30', 'year': 1999, 'timestamp': '2024-12-09 16:50:06', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903300CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 30 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:08
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 03, and day set to 31 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-03-31', 'year': 1999, 'timestamp': '2024-12-09 16:50:08', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199903310CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 03, and day set to 31 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:10
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 02 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-02', 'year': 1999, 'timestamp': '2024-12-09 16:50:10', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904020CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 02 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:12
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 05 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-05', 'year': 1999, 'timestamp': '2024-12-09 16:50:12', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904050CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 05 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:14
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 07 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-07', 'year': 1999, 'timestamp': '2024-12-09 16:50:14', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904070CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 07 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:16
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 09 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-09', 'year': 1999, 'timestamp': '2024-12-09 16:50:16', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904090CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 09 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:18
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 14 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-14', 'year': 1999, 'timestamp': '2024-12-09 16:50:18', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904140CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 14 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:20
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 21 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-21', 'year': 1999, 'timestamp': '2024-12-09 16:50:20', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904210CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 21 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:23
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 24 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-24', 'year': 1999, 'timestamp': '2024-12-09 16:50:23', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904240CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 24 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:25
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 26 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-26', 'year': 1999, 'timestamp': '2024-12-09 16:50:25', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904260CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 26 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:27
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 04, and day set to 30 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-04-30', 'year': 1999, 'timestamp': '2024-12-09 16:50:27', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199904300CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 04, and day set to 30 is invalid\n'}
==================================================

Time: 2024-12-09 16:50:29
Error Type: ProcessTeamGamesError
Error Message: Date with year set to 1999, month set to 05, and day set to 04 is invalid
Details: {'team': 'Team.CHARLOTTE_HORNETS', 'date': '1999-05-04', 'year': 1999, 'timestamp': '2024-12-09 16:50:29', 'traceback': 'Traceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 220, in play_by_play\n    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/http_service.py", line 100, in play_by_play\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.basketball-reference.com/boxscores/pbp/199905040CHO.html\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 1037, in main\n    player_yearAnalyzer.process_team_games(allTeams[team], curr_date[0], curr_date[1], curr_date[2], year, player_attemptCounter, best_ft_shooters, worst_ft_shooters, bestworst)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/eliyoung/Stat011Project/FatigueVSFreethrow/specificDataProcessor.py", line 66, in process_team_games\n    pbp_data = client.play_by_play(\n        home_team=team,\n    ...<2 lines>...\n        day=day\n    )\n  File "/Users/eliyoung/Stat011Project/myenv/lib/python3.13/site-packages/basketball_reference_web_scraper/client.py", line 223, in play_by_play\n    raise InvalidDate(day=day, month=month, year=year)\nbasketball_reference_web_scraper.errors.InvalidDate: Date with year set to 1999, month set to 05, and day set to 04 is invalid\n'}
==================================================

